# Question 1

### a)

$x_1 = \dfrac{1}{6} $\
$w_1 = \pi $\
$x_2 = \dfrac{1}{2} $\
$w_2 = \pi $

$f = \dfrac{1}{\sin^2\left(w_1x_1\right)+\cos\left(w_2x_2\right)+2}$

$\dfrac{df}{dW_1} = -\dfrac{2x_1\cos\left(x_1w_1\right)\sin\left(x_1w_1\right)}{\left(\sin^2\left(x_1w_1\right)+\cos\left(w_2x_2\right)+2\right)^2} = -0.0285$

$\dfrac{df}{dx_1} = -\dfrac{2w_1\cos\left(w_1x_1\right)\sin\left(w_1x_1\right)}{\left(\sin^2\left(w_1x_1\right)+\cos\left(w_2x_2\right)+2\right)^2} = -0.537$


$\dfrac{df}{dW_2} = \dfrac{x_2\sin\left(x_2w_2\right)}{\left(\cos\left(x_2w_2\right)+\sin^2\left(w_1x_1\right)+2\right)^2} = -0.09876$

$\dfrac{df}{dx_2} = \dfrac{w_2\sin\left(w_2x_2\right)}{\left(\cos\left(w_2x_2\right)+\sin^2\left(w_1x_1\right)+2\right)^2} = -0.6205$


### b)

In [201]:
import math

In [202]:
class ScalarNetwork ():
    def __init__(self,x1,w1,x2,w2):
        self.x1 = x1
        self.w1 = w1
        self.x2 = x2
        self.w2 = w2
    
    def fn_mul(self,x, w):
        return x*w
    
    def fn_sin2(self,x):
        return math.sin(x)**2
    
    def fn_cos(self,x):
        return math.cos(x)
    
    def fn_add(self,x,y):
        return x+y
    
    def fn_inv(self,x):
        return 1/x
    
    def diffp(self,fn, idx, *args): # partial direvative
        delta = 0.000000000001
        
        # Call the underlying function with args as such
        y = fn(*args)
        
        # Now, increase only one input - at idx.
        args = list(args)
        args[idx] += delta
        
        # Now, calulate the output after changing one of the inputs a little bit.
        y1 = fn(*args)
        return (y1 - y)/delta

    def forward(self):
        self.d = self.fn_mul(self.x1,self.w1) # d = x1*W1
        print("d = ",self.d)
        
        self.e = self.fn_mul(self.x2,self.w2) # e = x2*W2
        print("e = ",self.e)

        self.b = self.fn_sin2(self.d) # b = sin^2(d)
        print("b = ",self.b)

        self.c = self.fn_cos(self.e) # c = cos(e)
        print("c = ",self.c , " (aprrox. = 0)")

        self.a = self.fn_add(self.b , self.c) # a = b + c
        print("a = ",self.a)

        self.x = self.fn_add(self.a , 2) # x = a + 2
        print("x = ",self.x)

        self.output = self.fn_inv(self.x) # f = 1/x
        print("f or y = ", self.output)
    
    def backprop(self): # using numerical direviate, since we know the exact direviate trough chain rule ans. in (a)

        self.df = 1 # df/df = 1
        print("df = ",self.df)

        self.dx = self.df * self.diffp(self.fn_inv,0,self.x) # df/dx = df/df * df/dx 
        print("dx = ",self.dx)

        self.da = self.dx * self.diffp(self.fn_add,0,self.a,2) # df/da = df/dx * dx/da 
        print("da = ",self.dx)

        self.db = self.da * self.diffp(self.fn_add,0,self.b,self.c) # df/db = df/da * da/db 
        print("da = ",self.db)

        self.dc = self.da * self.diffp(self.fn_add,1,self.b,self.c) # df/dc = df/da * da/dc
        print("dc = ",self.dc)

        self.dd = self.db * self.diffp(self.fn_sin2,0,self.d) # df/dd = df/db * db/dd 
        print("dd = ",self.dd)

        self.de = self.dc * self.diffp(self.fn_cos,0,self.e) # df/de = df/dc * dc/de 
        print("de = ",self.de)

        self.dW1 = self.dd * self.diffp(self.fn_mul,1,self.x1,self.w1) # df/dW1 = df/dd * dd/dW1 
        print("\ndW1 = ",self.dW1)

        self.dx1 = self.dd * self.diffp(self.fn_mul,0,self.x1,self.w1) # df/dx1 = df/dd * dd/dx1 
        print("dx1 = ",self.dx1)

        self.dW2 = self.de * self.diffp(self.fn_mul,1,self.x2,self.w2) # df/dW1 = df/dd * dd/dW1 
        print("\ndW1 = ",self.dW2)
        
        self.dx2 = self.de * self.diffp(self.fn_mul,0,self.x2,self.w2) # df/dx1 = df/dd * dd/dx1 
        print("dx1 = ",self.dx2)
        
        




In [203]:
x1 = 1/6
w1 = math.pi

x2 = 1/2
w2 = math.pi

In [204]:
net = ScalarNetwork(x1,w1,x2,w2)

print("Forward Pass :-")
net.forward()

print("\nBackward Pass :-")
net.backprop()

Forward Pass :-
d =  0.5235987755982988
e =  1.5707963267948966
b =  0.24999999999999994
c =  6.123233995736766e-17  (aprrox. = 0)
a =  0.25
x =  2.25
f or y =  0.4444444444444444

Backward Pass :-
df =  1
dx =  -0.19750867608081535
da =  -0.19750867608081535
da =  -0.19752186509705527
dc =  -0.19753283000574282
dd =  -0.17105975621429567
de =  0.1975503907893618

dW1 =  -0.028506163438375177
dx1 =  -0.5374010038745519

dW1 =  0.09878397656707233
dx1 =  0.6206019984329215


_It can be seen that the answers approximately match to part a)_

# Question 2

### a)

$W = \begin{bmatrix}
0.1 & 0.2 & 0.4\\
0.3 & 0.5 & 0.7\\
0.6 & 0.9 & 0.8
\end{bmatrix}$

$x = \begin{bmatrix}
0.4\\
0.7\\
0.1
\end{bmatrix}$

$f = {|| \sigma{(Wx)} ||}^2$

$q = \sigma{(Wx)}$ 

$\dfrac{df}{dW} = 2* ([(1-q) \odot q] \cdot q ) * x^{T} = \begin{bmatrix}
0.109 & 0.190 & 0.0272\\
0.117 & 0.205 & 0.0293\\
0.116 & 0.203 & 0.0.289
\end{bmatrix}$

$\dfrac{df}{dx} = 2* W^{T} * ([(1-q) \odot q] \cdot q ) = \begin{bmatrix}
0.289\\
0.461\\
0.545
\end{bmatrix}$

### b)

In [205]:
import numpy as np
import copy

In [206]:
class VectorNetwork():
    def __init__(self,W,x):
        self.W = W
        self.x = x
    
    def fn_dot(self,W,x):
        return np.dot(W,x)
    

    def fn_sigmoid(self,m):
        return 1/(1 + np.exp(-1*m))
    
    def fn_L2(self,q):
        return np.linalg.norm(q)**2
    
    def jacobian(self,fn,idx,*args):
        delta = 0.000000000001

        args_list = list(args)
        y = fn(*args)

        if type(y) == np.float64:
            n = 1
        else:
            n = len(y)
        
        m = np.prod(np.shape(args_list[idx]))

        J = np.zeros((n, m))

        for i in range(n):
            for j_id,_ in np.ndenumerate(args_list[idx]):
                x = copy.deepcopy(args_list)

                x[idx][j_id] += delta

                y1 = fn(*x)

                if np.shape(args_list[idx])[0] == 1:
                    j =  j_id[1] 
                elif np.shape(args_list[idx])[1] == 1:
                    j = j =  j_id[0]
                else:   
                    j =  j_id[0]*np.shape(args_list[idx])[1] + j_id[1]


                result = ((y1 - y) / (delta))

                if type(result) != np.float64:
                    result = result[i]

                J[i,j] = result
        
        return J

    def forward(self):
        self.m = self.fn_dot(self.W,self.x) # m = W*x
        print("m :\n",self.m)

        self.q = self.fn_sigmoid(self.m) # q = sigmoid(m)
        print("\nq :\n",self.q)

        self.output = self.fn_L2(self.q) # f = ||q||^2
        print("\nf :\n",self.output)
    
    def backprop(self):
        self.df = 1

        self.dq = np.reshape(np.dot(self.df,self.jacobian(self.fn_L2,0,self.q)),np.shape(self.q))
        print("dq :\n",self.dq)

        self.dm = np.reshape(np.dot(self.jacobian(self.fn_sigmoid,0,self.m),self.dq),np.shape(self.m))
        print("\ndm :\n",self.dm)

        self.dW = np.reshape(np.dot(np.transpose(self.jacobian(self.fn_dot,0,self.W,self.x)),self.dm),np.shape(self.W))
        print("\ndW :\n",self.dW)

        self.dx = np.reshape(np.dot(np.transpose(self.jacobian(self.fn_dot,1,self.W,self.x)),self.dm),np.shape(self.x))
        print("\ndx :\n",self.dx)

        

In [207]:
W = np.array([[0.1,0.2,0.4],[0.3,0.5,0.7],[0.6,0.9,0.8]])

x = np.array([[0.4],[0.7],[0.1]])

In [208]:
net = VectorNetwork(W,x)
print("Forward Pass:-")
net.forward()

print("\nBackward Pass:-")
net.backprop()


Forward Pass:-
m :
 [[0.22]
 [0.54]
 [0.95]]

q :
 [[0.55477924]
 [0.63181242]
 [0.72111518]]

f :
 1.2269740308866302

Backward Pass:-
dq :
 [[1.10933485]
 [1.26387789]
 [1.44240175]]

dm :
 [[0.27390986]
 [0.29396754]
 [0.29017144]]

dW :
 [[0.1095676  0.1917433  0.0273919 ]
 [0.11759094 0.20577599 0.02940589]
 [0.11610467 0.20315095 0.02902617]]

dx :
 [[0.28966952]
 [0.46291949]
 [0.54748089]]


_Due to human rounding error, some numbers differ by a bit, but overall it can be observed all numbers closely match the numbers form part a)_